#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.1'
#use_frameworks!

target 'Service Online' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Service Online
  pod 'Alamofire'
  pod 'AlamofireImage', '~> 3.5'
  pod 'SideMenuController'
  
end
